defaults: &defaults
    docker:
        - image: cimg/openjdk:21.0

version: 2.1

orbs:
  maven: circleci/maven@1.0.3

jobs:
  run_checkstyle:
    <<: *defaults
    working_directory: /tmp/repos/smile-request-filter
    steps:
      - checkout
      - run:
          name: Pull smile commons code
          command: |
              export SMILE_COMMONS_VERSION=$(grep 'smile_commons\.version' pom.xml | head -1 | sed 's/<smile_commons\.version>//g' | sed 's|</smile_commons\.version>||' | tr -d '[:blank:]' | cut -f1) && \
              export SMILE_COMMONS_ORG=$(grep 'smile_commons\.group' pom.xml | head -1 | sed 's/<smile_commons\.group>//g' | sed 's|</smile_commons\.group>||' | tr -d '[:blank:]' | cut -d. -f3) && \
              cd .. && \
              git clone https://github.com/$SMILE_COMMONS_ORG/smile-commons.git && \
              cd smile-commons && \
              git fetch --tags && \
              git checkout ${SMILE_COMMONS_VERSION}
      - run:
          name: "Build project..."
          command: mvn clean install
      - run:
          name: "Run checkstyle plugin..."
          command: mvn checkstyle:checkstyle
      - run:
          name: "Validating checkstyle plugin report..."
          command: bash /tmp/repos/smile-commons/test/scripts/generate_checkstyle_report.sh /tmp/repos/smile-request-filter
      - store_artifacts:
          path: /tmp/repos/smile-request-filter/checkstyle_report_compiled.txt
          destination: /checkstyle_report.txt

workflows:
  run_mvn_checkstyle:
    jobs:
        - run_checkstyle
